<?php
/**
 * Script translations helper.
 *
 * @package Woodev\Framework\Handlers
 */

namespace Woodev\Framework\Handlers;

defined( 'ABSPATH' ) || exit;

if ( ! class_exists( '\Woodev\Framework\Handlers\Script_Translations' ) ) :
	/**
	 * Hands the framework's JS translations to a built admin bundle.
	 *
	 * PHP translations reach the browser through the `.mo`; a JS bundle's `__()` is answered by
	 * `@wordpress/i18n`, which only knows what `wp_set_script_translations()` told it. Until this
	 * helper existed that call was made nowhere, so every JS msgid rendered as written whatever the
	 * locale (#1032).
	 *
	 * The JSON files live in `languages/` and are named by HANDLE —
	 * `{domain}-{locale}-{handle}.json` — not by the md5 of the script path WordPress would
	 * otherwise derive. The framework is vendored at a different relative path in every plugin, so a
	 * path hash can never match one file shipped in the framework; the handle-named file is the first
	 * thing `load_script_textdomain()` looks for (wp-includes/l10n.php, `$handle_filename`). The
	 * files are generated by `npm run build:js-i18n` and gated by `npm run lint:js-i18n`.
	 *
	 * @since 2.0.2
	 */
	class Script_Translations {

		/** @var string the fixed framework text domain */
		public const TEXTDOMAIN = 'woodev-plugin-framework';

		/**
		 * Registers the framework's JSON translations for an enqueued bundle handle.
		 *
		 * Call it AFTER `wp_enqueue_script()` / `wp_register_script()` — WordPress ignores a handle
		 * it does not know yet and returns false (`WP_Scripts::set_translations()`, which also
		 * adds the `wp-i18n` dependency when the handle lacks it).
		 *
		 * @since 2.0.2
		 *
		 * @param \Woodev_Plugin $plugin the plugin instance (resolves the loaded framework copy)
		 * @param string         $handle the script handle of a built `src/` bundle
		 * @return bool whether WordPress accepted the registration
		 */
		public static function register( \Woodev_Plugin $plugin, string $handle ): bool {
			return (bool) wp_set_script_translations( $handle, self::TEXTDOMAIN, $plugin->get_framework_path() . '/languages' );
		}
	}

endif;
