<?php
/**
 * Classmap completeness test.
 *
 * Asserts every framework class/interface/trait is reachable via the generated classmap.
 * Guards the production-WSOD-on-first-boot failure class (see gotcha
 * box-packer-interface-unwired-in-includes): a class missing from the map would resolve in
 * tests via Composer's classmap but fatal in a real vendored boot where no Composer exists.
 *
 * @package Woodev\Tests\Unit
 */

namespace Woodev\Tests\Unit;

/**
 * @coversNothing
 */
final class ClassMapCompletenessTest extends TestCase {

	public function test_every_framework_symbol_is_in_the_classmap(): void {
		$root = dirname( __DIR__, 2 );
		$map  = require $root . '/woodev/class-map.php';

		$skip = [
			'woodev/bootstrap.php',
			'woodev/loader.php',
			'woodev/class-map.php',
			'woodev/class-framework-autoloader.php',
		];

		$missing    = [];
		$mislocated = [];
		$iterator   = new \RecursiveIteratorIterator(
			new \RecursiveDirectoryIterator( $root . '/woodev', \FilesystemIterator::SKIP_DOTS )
		);

		foreach ( $iterator as $file ) {
			if ( 'php' !== strtolower( $file->getExtension() ) ) {
				continue;
			}

			$relative = str_replace( '\\', '/', substr( $file->getPathname(), strlen( $root ) + 1 ) );

			if ( in_array( $relative, $skip, true ) ) {
				continue;
			}

			foreach ( $this->extract_symbols( (string) file_get_contents( $file->getPathname() ) ) as $fqcn ) {
				if ( ! array_key_exists( $fqcn, $map ) ) {
					$missing[] = $fqcn . ' (' . $relative . ')';
				} elseif ( $map[ $fqcn ] !== $relative ) {
					// Catches a moved/renamed file whose stale map entry points at the old
					// path: the autoloader would silently fail to load it (is_readable guard),
					// causing a downstream "class not found" WSOD on a real vendored boot.
					$mislocated[] = sprintf( '%s mapped to %s but declared in %s', $fqcn, $map[ $fqcn ], $relative );
				}
			}
		}

		$this->assertSame(
			[],
			$missing,
			"Classmap is stale — run `php bin/generate-class-map.php`. Missing:\n" . implode( "\n", $missing )
		);

		$this->assertSame(
			[],
			$mislocated,
			"Classmap has stale paths — run `php bin/generate-class-map.php`. Mislocated:\n" . implode( "\n", $mislocated )
		);
	}

	/**
	 * Guards the DEV autoloader, which the test above does not.
	 *
	 * `woodev/class-map.php` is generated by scanning the whole tree, so it cannot drift.
	 * `composer.json` → `autoload.classmap` is a HAND-MAINTAINED directory list, and PSR-4
	 * cannot cover the gap: framework files use WordPress naming (`class-foo-bar.php`), which
	 * the `Woodev\Framework\ => woodev/` rule never maps. A directory added on disk but not to
	 * that list leaves its classes unreachable for Composer entirely — silently, because a full
	 * suite run masks it (some other test's `require_once` has already loaded the file) and only
	 * an isolated run exposes it. That is exactly how #598 and the s100 `LocationServiceDefault`
	 * failure happened.
	 *
	 * @return void
	 */
	public function test_every_framework_symbol_is_reachable_by_the_dev_autoloader(): void {
		$root = dirname( __DIR__, 2 );
		$map  = require $root . '/woodev/class-map.php';

		$loaders = \Composer\Autoload\ClassLoader::getRegisteredLoaders();
		$this->assertNotEmpty( $loaders, 'No Composer ClassLoader is registered — cannot verify dev autoloading.' );

		$loader      = reset( $loaders );
		$unreachable = [];

		foreach ( array_keys( $map ) as $fqcn ) {
			if ( false === $loader->findFile( $fqcn ) ) {
				$unreachable[] = $fqcn . ' (' . $map[ $fqcn ] . ')';
			}
		}

		sort( $unreachable );

		$this->assertSame(
			[],
			$unreachable,
			self::explain_unreachable( $root, $map, $unreachable )
		);
	}

	/**
	 * Names the LIKELY cause first, because the two causes need opposite responses and this
	 * message used to lead with the rarer one.
	 *
	 * A class can be unreachable for two reasons. Either its directory is missing from
	 * `composer.json` -> `autoload.classmap`, which is a real wiring defect; or the directory
	 * IS listed and Composer's `vendor/composer/autoload_classmap.php` is merely a STALE
	 * snapshot, which is not a defect in the tree at all. `vendor/` is gitignored, so git never
	 * refreshes that snapshot: pull or check out a branch that added a class and the file on
	 * disk still predates it. CI never sees this, because it installs from scratch every run.
	 *
	 * The old message gave the wiring advice for BOTH cases, which sends the reader hunting a
	 * bug that is usually not there. In s121 that misdirection cost two people time - a critic
	 * in its worktree and the coordinator in the main checkout - and then became the first line
	 * of the next session's handoff. The `post-merge`/`post-checkout` hooks in `.githooks/`
	 * remove the cause; this message is the safety net for a clone that never ran
	 * `git config core.hooksPath .githooks` (issue #802).
	 *
	 * @param string                $root        Repository root.
	 * @param array<string, string> $map         Generated class map, FQCN => relative path.
	 * @param string[]              $unreachable Rendered "FQCN (path)" entries, already sorted.
	 *
	 * @return string
	 */
	private static function explain_unreachable( string $root, array $map, array $unreachable ): string {
		$composer = json_decode( (string) file_get_contents( $root . '/composer.json' ), true );
		$listed   = (array) ( $composer['autoload']['classmap'] ?? [] );

		$stale   = [];
		$unwired = [];

		foreach ( $unreachable as $entry ) {
			$fqcn      = (string) strtok( $entry, ' ' );
			$path      = ltrim( $map[ $fqcn ] ?? '', './' );
			$is_listed = false;

			foreach ( $listed as $dir ) {
				if ( '' !== $path && 0 === strpos( $path, ltrim( (string) $dir, './' ) ) ) {
					$is_listed = true;
					break;
				}
			}

			if ( $is_listed ) {
				$stale[] = $entry;
			} else {
				$unwired[] = $entry;
			}
		}

		if ( [] === $unwired ) {
			return "STALE COMPOSER SNAPSHOT - this is NOT a defect in the tree.
"
				. "Run `composer dump-autoload` and re-run. Every class below sits in a directory that
"
				. "composer.json -> autoload.classmap ALREADY lists, so only the generated snapshot under
"
				. "vendor/ is behind - git does not refresh it, because for git it is not a build step.
"
				. "Enable the hooks that do it for you: `git config core.hooksPath .githooks`.

"
				. implode( "
", $stale );
		}

		$message = "Composer cannot autoload these framework classes. Their directory is missing from
"
			. "composer.json -> autoload.classmap - add it there, then run `composer dump-autoload`:

"
			. implode( "
", $unwired );

		if ( [] !== $stale ) {
			$message .= "

Separately, these are only a STALE snapshot (their directory is already
"
				. "listed) - `composer dump-autoload` alone fixes them:

" . implode( "
", $stale );
		}

		return $message;
	}

	/**
	 * Guards the REVERSE direction for the shipping module specifically (issue #138):
	 * every `woodev/shipping-method/**` class-map entry must also be wired into
	 * `Shipping_Plugin::includes()`. Unlike the rest of the framework — which the s27
	 * runtime autoloader deliberately made autoload-only, no `includes()` equivalent
	 * anywhere — the shipping module kept a hand-maintained `includes()` as its single
	 * source of truth (see `docs-internal/adr/012-shipping-includes-stays-authoritative.md`).
	 * A class added to the shipping tree without a matching `require_once` is exactly
	 * the failure class the gotchas `dispatcher-files-unwired-in-includes` and
	 * `box-packer-interface-unwired-in-includes` describe, just in the direction those
	 * two incidents did NOT check: this test catches the class the map knows about that
	 * `includes()` has never heard of, not the other way around.
	 *
	 * @return void
	 */
	public function test_every_shipping_classmap_entry_is_wired_into_includes(): void {
		$root = dirname( __DIR__, 2 );
		$map  = require $root . '/woodev/class-map.php';

		$self = 'woodev/shipping-method/class-shipping-plugin.php';

		$shipping_paths = array_unique(
			array_filter(
				$map,
				static function ( string $path ) use ( $self ): bool {
					return 0 === strpos( $path, 'woodev/shipping-method/' ) && $self !== $path;
				}
			)
		);

		$required = $this->extract_required_shipping_paths( $root );

		$missing = array_values( array_diff( $shipping_paths, $required ) );
		sort( $missing );

		$this->assertSame(
			[],
			$missing,
			"Shipping_Plugin::includes() is missing a require_once for a class the classmap already knows about:\n"
				. implode( "\n", $missing )
		);
	}

	/**
	 * Guards the OTHER half of issue #138 — the half the map-side test above cannot see.
	 *
	 * Deleting a required file (four production fatals on `feat/pickup-map`, per the card) leaves
	 * a `require_once` pointing at nothing. `bin/generate-class-map.php` drops the deleted file
	 * from the map on its next run, same as the test above expects — so the map-side assertion
	 * reports zero missing entries, stays green, and the dangling `require_once` still fatals a
	 * real vendored boot. Asserting the file exists catches that directly, and does not
	 * false-positive on a legitimately class-less required file (there are none today, but nothing
	 * stops one — a constants/functions file requires no class-map entry).
	 *
	 * @return void
	 */
	public function test_every_required_shipping_file_exists(): void {
		$root = dirname( __DIR__, 2 );

		$missing = [];

		foreach ( $this->extract_required_shipping_paths( $root ) as $relative ) {
			if ( ! file_exists( $root . '/' . $relative ) ) {
				$missing[] = $relative;
			}
		}

		sort( $missing );

		$this->assertSame(
			[],
			$missing,
			"Shipping_Plugin::includes() has a require_once pointing at a file that no longer exists — "
				. "this is the exact fatal a real vendored boot hits. Missing:\n" . implode( "\n", $missing )
		);
	}

	/**
	 * Extracts the `require_once $path . '...'` targets from `Shipping_Plugin::includes()`,
	 * relative to the repo root.
	 *
	 * @param string $root Repo root (dirname( __DIR__, 2 )).
	 * @return string[]
	 */
	private function extract_required_shipping_paths( string $root ): array {
		$self = 'woodev/shipping-method/class-shipping-plugin.php';

		$source = (string) file_get_contents( $root . '/' . $self );

		preg_match_all( "/require_once\s+\\\$path\s*\.\s*'([^']+)'/", $source, $matches );

		return array_map(
			static function ( string $relative ): string {
				return 'woodev/shipping-method' . $relative;
			},
			$matches[1]
		);
	}

	/**
	 * Extracts fully-qualified class/interface/trait names from PHP source via tokens.
	 *
	 * @param string $source PHP source.
	 * @return string[]
	 */
	private function extract_symbols( string $source ): array {
		$tokens    = token_get_all( $source );
		$namespace = '';
		$symbols   = [];
		$count     = count( $tokens );

		for ( $i = 0; $i < $count; $i++ ) {
			$token = $tokens[ $i ];

			if ( is_array( $token ) && T_NAMESPACE === $token[0] ) {
				$namespace = '';
				for ( $j = $i + 1; $j < $count; $j++ ) {
					$next = $tokens[ $j ];
					if ( ';' === $next || '{' === $next ) {
						break;
					}
					if ( is_array( $next ) && in_array( $next[0], [ T_STRING, T_NS_SEPARATOR ], true ) ) {
						$namespace .= $next[1];
					}
					if ( is_array( $next ) && defined( 'T_NAME_QUALIFIED' ) && T_NAME_QUALIFIED === $next[0] ) {
						$namespace .= $next[1];
					}
				}
				continue;
			}

			$class_like = [ T_CLASS, T_INTERFACE, T_TRAIT ];
			if ( defined( 'T_ENUM' ) ) {
				$class_like[] = T_ENUM;
			}

			if ( is_array( $token ) && in_array( $token[0], $class_like, true ) ) {
				$prev = $tokens[ $i - 1 ] ?? null;
				if ( is_array( $prev ) && T_DOUBLE_COLON === $prev[0] ) {
					continue;
				}
				for ( $j = $i + 1; $j < $count; $j++ ) {
					$next = $tokens[ $j ];
					if ( is_array( $next ) && T_WHITESPACE === $next[0] ) {
						continue;
					}
					if ( is_array( $next ) && T_STRING === $next[0] ) {
						$symbols[] = '' !== $namespace ? $namespace . '\\' . $next[1] : $next[1];
					}
					break;
				}
			}
		}

		return $symbols;
	}
}
